baseURL = 'https://codefrydev.in/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Code Fry Dev'

[Author]
  name = "CodeFryDev"

[Params]
  description = "Building software products, apps, and developer tools for web, mobile, and desktop, providing AI-ready boilerplate code to accelerate feature implementation."
  logo = "favicon-32x32.png"
  copyright = "codefrydev.in"

[params]
  paginate = 10  # Number of posts per page
  env = "production"
  google_analytics_id = "G-VM01Q3R43D"
  
  [assets]
    favicon = "favicon.ico"
    favicon16x16 = "favicon-16x16.png"
    favicon32x32 = "favicon-32x32.png"
    apple_touch_icon = "apple-touch-icon.png"
    safari_pinned_tab = "safari-pinned-tab.svg"
  
  [label]
    text = "CodeFryDev"
    icon = "favicon.ico"
    iconHeight = 35

  [sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content"

